"""Fix server enums to use native enum

Revision ID: 3e773d825d41
Revises: f14235f9eab8
Create Date: 2025-10-17 14:52:02.990428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e773d825d41'
down_revision: Union[str, Sequence[str], None] = 'f14235f9eab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deployments', 'type',
               existing_type=postgresql.ENUM('manual', 'automatic', 'rollback', name='deployment_type'),
               type_=sa.Enum('manual', 'automatic', 'rollback', name='deploymenttype'),
               existing_comment='배포 타입',
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::deployment_type"))
    op.alter_column('deployments', 'status',
               existing_type=postgresql.ENUM('pending', 'in_progress', 'success', 'failed', 'rolled_back', name='deployment_status'),
               type_=sa.Enum('pending', 'in_progress', 'success', 'failed', 'rolled_back', name='deploymentstatus'),
               existing_comment='배포 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::deployment_status"))
    op.alter_column('deployments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deployments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_deployments_deployed_by', table_name='deployments')
    op.drop_index('idx_deployments_env_status', table_name='deployments')
    op.drop_index('idx_deployments_environment', table_name='deployments')
    op.drop_index('idx_deployments_service_created', table_name='deployments')
    op.drop_index('idx_deployments_service_env', table_name='deployments')
    op.drop_index('idx_deployments_service_id', table_name='deployments')
    op.drop_index('idx_deployments_service_status', table_name='deployments')
    op.drop_index('idx_deployments_status', table_name='deployments')
    op.drop_index('idx_deployments_type', table_name='deployments')
    op.create_index(op.f('ix_deployments_environment'), 'deployments', ['environment'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.drop_table_comment(
        'deployments',
        existing_comment='배포 테이블 - 서비스의 배포 이력 추적',
        schema=None
    )
    op.alter_column('issues', 'sprint_id',
               existing_type=sa.INTEGER(),
               comment='스프린트 ID',
               existing_comment='스프린트 ID (백로그 이슈는 NULL)',
               existing_nullable=True)
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_issues_assignee_id', table_name='issues')
    op.drop_index('idx_issues_assignee_status', table_name='issues')
    op.drop_index('idx_issues_creator_id', table_name='issues')
    op.drop_index('idx_issues_key', table_name='issues')
    op.drop_index('idx_issues_priority', table_name='issues')
    op.drop_index('idx_issues_project_id', table_name='issues')
    op.drop_index('idx_issues_project_sprint', table_name='issues')
    op.drop_index('idx_issues_project_status', table_name='issues')
    op.drop_index('idx_issues_sprint_id', table_name='issues')
    op.drop_index('idx_issues_sprint_status', table_name='issues')
    op.drop_index('idx_issues_status', table_name='issues')
    op.drop_index('idx_issues_type', table_name='issues')
    op.drop_constraint('issues_key_key', 'issues', type_='unique')
    op.create_index(op.f('ix_issues_key'), 'issues', ['key'], unique=True)
    op.create_index(op.f('ix_issues_priority'), 'issues', ['priority'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_type'), 'issues', ['type'], unique=False)
    op.drop_table_comment(
        'issues',
        existing_comment='이슈 테이블 - 작업, 버그, 기능 요청 등을 추적',
        schema=None
    )
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_projects_key', table_name='projects')
    op.drop_index('idx_projects_name', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_team_id', table_name='projects')
    op.drop_constraint('projects_key_key', 'projects', type_='unique')
    op.create_index(op.f('ix_projects_key'), 'projects', ['key'], unique=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.drop_table_comment(
        'projects',
        existing_comment='프로젝트 테이블 - 개발 프로젝트 정보',
        schema=None
    )
    op.alter_column('servers', 'type',
               existing_type=postgresql.ENUM('physical', 'virtual', 'cloud', 'container', name='server_type'),
               type_=sa.Enum('physical', 'virtual', 'cloud', 'container', name='servertype'),
               existing_comment='서버 타입',
               existing_nullable=False,
               existing_server_default=sa.text("'virtual'::server_type"))
    op.alter_column('servers', 'status',
               existing_type=postgresql.ENUM('active', 'inactive', 'maintenance', 'decommissioned', name='server_status'),
               type_=sa.Enum('active', 'inactive', 'maintenance', 'decommissioned', name='serverstatus'),
               existing_comment='서버 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::server_status"))
    op.alter_column('servers', 'description',
               existing_type=sa.TEXT(),
               comment='서버 설명',
               existing_nullable=True)
    op.alter_column('servers', 'notes',
               existing_type=sa.TEXT(),
               comment='비고',
               existing_nullable=True)
    op.alter_column('servers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('servers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_servers_env_status', table_name='servers')
    op.drop_index('idx_servers_environment', table_name='servers')
    op.drop_index('idx_servers_hostname', table_name='servers')
    op.drop_index('idx_servers_name', table_name='servers')
    op.drop_index('idx_servers_status', table_name='servers')
    op.drop_index('idx_servers_type', table_name='servers')
    op.drop_constraint('servers_name_key', 'servers', type_='unique')
    op.create_index(op.f('ix_servers_environment'), 'servers', ['environment'], unique=False)
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=True)
    op.create_index(op.f('ix_servers_status'), 'servers', ['status'], unique=False)
    op.create_index(op.f('ix_servers_type'), 'servers', ['type'], unique=False)
    op.drop_table_comment(
        'servers',
        existing_comment='서버 테이블 - 물리/가상 서버, 클라우드 인스턴스 정보',
        schema=None
    )
    op.alter_column('services', 'type',
               existing_type=postgresql.ENUM('web', 'api', 'database', 'cache', 'queue', 'worker', 'cron', 'other', name='service_type'),
               type_=sa.Enum('web', 'api', 'database', 'cache', 'queue', 'worker', 'cron', 'other', name='servicetype'),
               existing_comment='서비스 타입',
               existing_nullable=False,
               existing_server_default=sa.text("'web'::service_type"))
    op.alter_column('services', 'status',
               existing_type=postgresql.ENUM('running', 'stopped', 'degraded', 'maintenance', 'failed', name='service_status'),
               type_=sa.Enum('running', 'stopped', 'degraded', 'maintenance', 'failed', name='servicestatus'),
               existing_comment='서비스 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'stopped'::service_status"))
    op.alter_column('services', 'environment_variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_comment='환경 변수 (JSON)',
               existing_nullable=True)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               comment='서비스 설명',
               existing_nullable=True)
    op.alter_column('services', 'notes',
               existing_type=sa.TEXT(),
               comment='비고',
               existing_nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_services_name', table_name='services')
    op.drop_index('idx_services_server_id', table_name='services')
    op.drop_index('idx_services_server_status', table_name='services')
    op.drop_index('idx_services_status', table_name='services')
    op.drop_index('idx_services_type', table_name='services')
    op.drop_index('idx_services_type_status', table_name='services')
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_index(op.f('ix_services_type'), 'services', ['type'], unique=False)
    op.drop_table_comment(
        'services',
        existing_comment='서비스 테이블 - 서버에서 실행되는 애플리케이션 서비스',
        schema=None
    )
    op.alter_column('sprints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sprints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_sprints_dates', table_name='sprints')
    op.drop_index('idx_sprints_project_id', table_name='sprints')
    op.drop_index('idx_sprints_project_status', table_name='sprints')
    op.drop_index('idx_sprints_status', table_name='sprints')
    op.create_index(op.f('ix_sprints_status'), 'sprints', ['status'], unique=False)
    op.drop_table_comment(
        'sprints',
        existing_comment='스프린트 테이블 - 애자일 스프린트 정보',
        schema=None
    )
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='team_role'),
               type_=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='teamrole', native_enum=False, length=20),
               comment='팀 내 역할',
               existing_comment='팀 내 역할 (owner, admin, member, viewer)',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::team_role"))
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_team_members_role', table_name='team_members')
    op.drop_index('idx_team_members_team_id', table_name='team_members')
    op.drop_index('idx_team_members_team_user', table_name='team_members')
    op.drop_index('idx_team_members_user_id', table_name='team_members')
    op.drop_constraint('team_members_team_id_user_id_key', 'team_members', type_='unique')
    op.drop_table_comment(
        'team_members',
        existing_comment='팀 멤버 테이블 - 팀과 사용자의 다대다 관계',
        schema=None
    )
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_teams_name', table_name='teams')
    op.drop_index('idx_teams_slug', table_name='teams')
    op.drop_constraint('teams_name_key', 'teams', type_='unique')
    op.drop_constraint('teams_slug_key', 'teams', type_='unique')
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.drop_table_comment(
        'teams',
        existing_comment='팀 테이블 - 프로젝트를 관리하는 팀',
        schema=None
    )
    op.alter_column('users', 'authentik_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Authentik 사용자 ID',
               existing_comment='Authentik SSO 사용자 ID',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='이메일',
               existing_comment='이메일 주소',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_users_authentik_id', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_is_active', table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_constraint('users_authentik_id_key', 'users', type_='unique')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_authentik_id'), 'users', ['authentik_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='사용자 테이블 - Authentik과 연동되는 사용자 정보',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '사용자 테이블 - Authentik과 연동되는 사용자 정보',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_authentik_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_unique_constraint('users_authentik_id_key', 'users', ['authentik_id'])
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index('idx_users_is_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_authentik_id', 'users', ['authentik_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='이메일 주소',
               existing_comment='이메일',
               existing_nullable=False)
    op.alter_column('users', 'authentik_id',
               existing_type=sa.VARCHAR(length=255),
               comment='Authentik SSO 사용자 ID',
               existing_comment='Authentik 사용자 ID',
               existing_nullable=False)
    op.create_table_comment(
        'teams',
        '팀 테이블 - 프로젝트를 관리하는 팀',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.create_unique_constraint('teams_slug_key', 'teams', ['slug'])
    op.create_unique_constraint('teams_name_key', 'teams', ['name'])
    op.create_index('idx_teams_slug', 'teams', ['slug'], unique=False)
    op.create_index('idx_teams_name', 'teams', ['name'], unique=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'team_members',
        '팀 멤버 테이블 - 팀과 사용자의 다대다 관계',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint('team_members_team_id_user_id_key', 'team_members', ['team_id', 'user_id'])
    op.create_index('idx_team_members_user_id', 'team_members', ['user_id'], unique=False)
    op.create_index('idx_team_members_team_user', 'team_members', ['team_id', 'user_id'], unique=False)
    op.create_index('idx_team_members_team_id', 'team_members', ['team_id'], unique=False)
    op.create_index('idx_team_members_role', 'team_members', ['role'], unique=False)
    op.alter_column('team_members', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('team_members', 'role',
               existing_type=sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='teamrole', native_enum=False, length=20),
               type_=postgresql.ENUM('owner', 'admin', 'member', 'viewer', name='team_role'),
               comment='팀 내 역할 (owner, admin, member, viewer)',
               existing_comment='팀 내 역할',
               existing_nullable=False,
               existing_server_default=sa.text("'member'::team_role"))
    op.create_table_comment(
        'sprints',
        '스프린트 테이블 - 애자일 스프린트 정보',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_sprints_status'), table_name='sprints')
    op.create_index('idx_sprints_status', 'sprints', ['status'], unique=False)
    op.create_index('idx_sprints_project_status', 'sprints', ['project_id', 'status'], unique=False)
    op.create_index('idx_sprints_project_id', 'sprints', ['project_id'], unique=False)
    op.create_index('idx_sprints_dates', 'sprints', ['start_date', 'end_date'], unique=False)
    op.alter_column('sprints', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sprints', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'services',
        '서비스 테이블 - 서버에서 실행되는 애플리케이션 서비스',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_services_type'), table_name='services')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.create_index('idx_services_type_status', 'services', ['type', 'status'], unique=False)
    op.create_index('idx_services_type', 'services', ['type'], unique=False)
    op.create_index('idx_services_status', 'services', ['status'], unique=False)
    op.create_index('idx_services_server_status', 'services', ['server_id', 'status'], unique=False)
    op.create_index('idx_services_server_id', 'services', ['server_id'], unique=False)
    op.create_index('idx_services_name', 'services', ['name'], unique=False)
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('services', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='비고',
               existing_nullable=True)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='서비스 설명',
               existing_nullable=True)
    op.alter_column('services', 'environment_variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_comment='환경 변수 (JSON)',
               existing_nullable=True)
    op.alter_column('services', 'status',
               existing_type=sa.Enum('running', 'stopped', 'degraded', 'maintenance', 'failed', name='servicestatus'),
               type_=postgresql.ENUM('running', 'stopped', 'degraded', 'maintenance', 'failed', name='service_status'),
               existing_comment='서비스 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'stopped'::service_status"))
    op.alter_column('services', 'type',
               existing_type=sa.Enum('web', 'api', 'database', 'cache', 'queue', 'worker', 'cron', 'other', name='servicetype'),
               type_=postgresql.ENUM('web', 'api', 'database', 'cache', 'queue', 'worker', 'cron', 'other', name='service_type'),
               existing_comment='서비스 타입',
               existing_nullable=False,
               existing_server_default=sa.text("'web'::service_type"))
    op.create_table_comment(
        'servers',
        '서버 테이블 - 물리/가상 서버, 클라우드 인스턴스 정보',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_servers_type'), table_name='servers')
    op.drop_index(op.f('ix_servers_status'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_index(op.f('ix_servers_environment'), table_name='servers')
    op.create_unique_constraint('servers_name_key', 'servers', ['name'])
    op.create_index('idx_servers_type', 'servers', ['type'], unique=False)
    op.create_index('idx_servers_status', 'servers', ['status'], unique=False)
    op.create_index('idx_servers_name', 'servers', ['name'], unique=False)
    op.create_index('idx_servers_hostname', 'servers', ['hostname'], unique=False)
    op.create_index('idx_servers_environment', 'servers', ['environment'], unique=False)
    op.create_index('idx_servers_env_status', 'servers', ['environment', 'status'], unique=False)
    op.alter_column('servers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('servers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('servers', 'notes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='비고',
               existing_nullable=True)
    op.alter_column('servers', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='서버 설명',
               existing_nullable=True)
    op.alter_column('servers', 'status',
               existing_type=sa.Enum('active', 'inactive', 'maintenance', 'decommissioned', name='serverstatus'),
               type_=postgresql.ENUM('active', 'inactive', 'maintenance', 'decommissioned', name='server_status'),
               existing_comment='서버 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::server_status"))
    op.alter_column('servers', 'type',
               existing_type=sa.Enum('physical', 'virtual', 'cloud', 'container', name='servertype'),
               type_=postgresql.ENUM('physical', 'virtual', 'cloud', 'container', name='server_type'),
               existing_comment='서버 타입',
               existing_nullable=False,
               existing_server_default=sa.text("'virtual'::server_type"))
    op.create_table_comment(
        'projects',
        '프로젝트 테이블 - 개발 프로젝트 정보',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_key'), table_name='projects')
    op.create_unique_constraint('projects_key_key', 'projects', ['key'])
    op.create_index('idx_projects_team_id', 'projects', ['team_id'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_name', 'projects', ['name'], unique=False)
    op.create_index('idx_projects_key', 'projects', ['key'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'issues',
        '이슈 테이블 - 작업, 버그, 기능 요청 등을 추적',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_issues_type'), table_name='issues')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_priority'), table_name='issues')
    op.drop_index(op.f('ix_issues_key'), table_name='issues')
    op.create_unique_constraint('issues_key_key', 'issues', ['key'])
    op.create_index('idx_issues_type', 'issues', ['type'], unique=False)
    op.create_index('idx_issues_status', 'issues', ['status'], unique=False)
    op.create_index('idx_issues_sprint_status', 'issues', ['sprint_id', 'status'], unique=False)
    op.create_index('idx_issues_sprint_id', 'issues', ['sprint_id'], unique=False)
    op.create_index('idx_issues_project_status', 'issues', ['project_id', 'status'], unique=False)
    op.create_index('idx_issues_project_sprint', 'issues', ['project_id', 'sprint_id'], unique=False)
    op.create_index('idx_issues_project_id', 'issues', ['project_id'], unique=False)
    op.create_index('idx_issues_priority', 'issues', ['priority'], unique=False)
    op.create_index('idx_issues_key', 'issues', ['key'], unique=False)
    op.create_index('idx_issues_creator_id', 'issues', ['creator_id'], unique=False)
    op.create_index('idx_issues_assignee_status', 'issues', ['assignee_id', 'status'], unique=False)
    op.create_index('idx_issues_assignee_id', 'issues', ['assignee_id'], unique=False)
    op.alter_column('issues', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('issues', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('issues', 'sprint_id',
               existing_type=sa.INTEGER(),
               comment='스프린트 ID (백로그 이슈는 NULL)',
               existing_comment='스프린트 ID',
               existing_nullable=True)
    op.create_table_comment(
        'deployments',
        '배포 테이블 - 서비스의 배포 이력 추적',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment'), table_name='deployments')
    op.create_index('idx_deployments_type', 'deployments', ['type'], unique=False)
    op.create_index('idx_deployments_status', 'deployments', ['status'], unique=False)
    op.create_index('idx_deployments_service_status', 'deployments', ['service_id', 'status'], unique=False)
    op.create_index('idx_deployments_service_id', 'deployments', ['service_id'], unique=False)
    op.create_index('idx_deployments_service_env', 'deployments', ['service_id', 'environment'], unique=False)
    op.create_index('idx_deployments_service_created', 'deployments', ['service_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_deployments_environment', 'deployments', ['environment'], unique=False)
    op.create_index('idx_deployments_env_status', 'deployments', ['environment', 'status'], unique=False)
    op.create_index('idx_deployments_deployed_by', 'deployments', ['deployed_by'], unique=False)
    op.alter_column('deployments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='수정일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deployments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='생성일시',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('deployments', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'success', 'failed', 'rolled_back', name='deploymentstatus'),
               type_=postgresql.ENUM('pending', 'in_progress', 'success', 'failed', 'rolled_back', name='deployment_status'),
               existing_comment='배포 상태',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::deployment_status"))
    op.alter_column('deployments', 'type',
               existing_type=sa.Enum('manual', 'automatic', 'rollback', name='deploymenttype'),
               type_=postgresql.ENUM('manual', 'automatic', 'rollback', name='deployment_type'),
               existing_comment='배포 타입',
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::deployment_type"))
    # ### end Alembic commands ###
