"""Initial migration: create all tables

Revision ID: 54312775cac4
Revises: 
Create Date: 2025-10-16 01:03:34.503872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54312775cac4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers',
    sa.Column('id', sa.Integer(), nullable=False, comment='서버 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='서버 이름'),
    sa.Column('hostname', sa.String(length=255), nullable=False, comment='호스트명'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IP 주소 (IPv4/IPv6)'),
    sa.Column('type', sa.Enum('PHYSICAL', 'VIRTUAL', 'CLOUD', 'CONTAINER', name='servertype', native_enum=False, length=20), nullable=False, comment='서버 타입'),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'DECOMMISSIONED', name='serverstatus', native_enum=False, length=20), nullable=False, comment='서버 상태'),
    sa.Column('environment', sa.String(length=50), nullable=False, comment='환경 (dev, staging, production)'),
    sa.Column('cpu_cores', sa.Integer(), nullable=True, comment='CPU 코어 수'),
    sa.Column('memory_gb', sa.Integer(), nullable=True, comment='메모리 (GB)'),
    sa.Column('disk_gb', sa.Integer(), nullable=True, comment='디스크 용량 (GB)'),
    sa.Column('os_name', sa.String(length=100), nullable=True, comment='운영체제 이름'),
    sa.Column('os_version', sa.String(length=50), nullable=True, comment='운영체제 버전'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='클라우드 제공자 (AWS, GCP, Azure 등)'),
    sa.Column('region', sa.String(length=50), nullable=True, comment='리전'),
    sa.Column('instance_id', sa.String(length=100), nullable=True, comment='인스턴스 ID'),
    sa.Column('ssh_port', sa.Integer(), nullable=False, comment='SSH 포트'),
    sa.Column('ssh_user', sa.String(length=50), nullable=True, comment='SSH 사용자명'),
    sa.Column('monitoring_enabled', sa.Boolean(), nullable=False, comment='모니터링 활성화 여부'),
    sa.Column('monitoring_url', sa.String(length=500), nullable=True, comment='모니터링 대시보드 URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='서버 설명'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_index(op.f('ix_servers_environment'), 'servers', ['environment'], unique=False)
    op.create_index(op.f('ix_servers_name'), 'servers', ['name'], unique=True)
    op.create_index(op.f('ix_servers_status'), 'servers', ['status'], unique=False)
    op.create_index(op.f('ix_servers_type'), 'servers', ['type'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False, comment='팀 ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='팀 이름'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='팀 설명'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='팀 슬러그 (URL용)'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='팀 로고 이미지 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_index(op.f('ix_teams_slug'), 'teams', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('authentik_id', sa.String(length=255), nullable=False, comment='Authentik 사용자 ID'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='사용자명'),
    sa.Column('full_name', sa.String(length=200), nullable=True, comment='전체 이름'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='프로필 이미지 URL'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('is_admin', sa.Boolean(), nullable=False, comment='관리자 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_authentik_id'), 'users', ['authentik_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False, comment='프로젝트 ID'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='팀 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='프로젝트 이름'),
    sa.Column('key', sa.String(length=10), nullable=False, comment='프로젝트 키 (예: PROJ, DEV)'),
    sa.Column('description', sa.Text(), nullable=True, comment='프로젝트 설명'),
    sa.Column('status', sa.Enum('PLANNING', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'ARCHIVED', name='projectstatus', native_enum=False, length=20), nullable=False, comment='프로젝트 상태'),
    sa.Column('repository_url', sa.String(length=500), nullable=True, comment='Git 리포지토리 URL'),
    sa.Column('documentation_url', sa.String(length=500), nullable=True, comment='문서 URL'),
    sa.Column('icon_url', sa.String(length=500), nullable=True, comment='프로젝트 아이콘 URL'),
    sa.Column('color', sa.String(length=7), nullable=True, comment='프로젝트 색상 (HEX)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_key'), 'projects', ['key'], unique=True)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False, comment='서비스 ID'),
    sa.Column('server_id', sa.Integer(), nullable=False, comment='서버 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='서비스 이름'),
    sa.Column('type', sa.Enum('WEB', 'API', 'DATABASE', 'CACHE', 'QUEUE', 'WORKER', 'CRON', 'OTHER', name='servicetype', native_enum=False, length=20), nullable=False, comment='서비스 타입'),
    sa.Column('status', sa.Enum('RUNNING', 'STOPPED', 'DEGRADED', 'MAINTENANCE', 'FAILED', name='servicestatus', native_enum=False, length=20), nullable=False, comment='서비스 상태'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='서비스 버전'),
    sa.Column('port', sa.Integer(), nullable=True, comment='서비스 포트'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='서비스 URL'),
    sa.Column('process_name', sa.String(length=200), nullable=True, comment='프로세스 이름'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='프로세스 ID'),
    sa.Column('container_id', sa.String(length=100), nullable=True, comment='컨테이너 ID (Docker 등)'),
    sa.Column('image_name', sa.String(length=200), nullable=True, comment='컨테이너 이미지 이름'),
    sa.Column('cpu_limit', sa.Integer(), nullable=True, comment='CPU 제한 (%)'),
    sa.Column('memory_limit_mb', sa.Integer(), nullable=True, comment='메모리 제한 (MB)'),
    sa.Column('health_check_url', sa.String(length=500), nullable=True, comment='헬스체크 URL'),
    sa.Column('health_check_enabled', sa.Boolean(), nullable=False, comment='헬스체크 활성화 여부'),
    sa.Column('environment_variables', sa.JSON(), nullable=True, comment='환경 변수 (JSON)'),
    sa.Column('config_path', sa.String(length=500), nullable=True, comment='설정 파일 경로'),
    sa.Column('log_path', sa.String(length=500), nullable=True, comment='로그 파일 경로'),
    sa.Column('auto_start', sa.Boolean(), nullable=False, comment='서버 부팅 시 자동 시작 여부'),
    sa.Column('description', sa.Text(), nullable=True, comment='서비스 설명'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    op.create_index(op.f('ix_services_status'), 'services', ['status'], unique=False)
    op.create_index(op.f('ix_services_type'), 'services', ['type'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False, comment='팀 멤버 ID'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='팀 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='teamrole', native_enum=False, length=20), nullable=False, comment='팀 내 역할'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), nullable=False, comment='배포 ID'),
    sa.Column('service_id', sa.Integer(), nullable=False, comment='서비스 ID'),
    sa.Column('deployed_by', sa.Integer(), nullable=False, comment='배포 실행자 ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='배포 버전'),
    sa.Column('commit_hash', sa.String(length=40), nullable=True, comment='Git 커밋 해시'),
    sa.Column('branch', sa.String(length=100), nullable=True, comment='Git 브랜치'),
    sa.Column('tag', sa.String(length=100), nullable=True, comment='Git 태그'),
    sa.Column('type', sa.Enum('MANUAL', 'AUTOMATIC', 'ROLLBACK', name='deploymenttype', native_enum=False, length=20), nullable=False, comment='배포 타입'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'ROLLED_BACK', name='deploymentstatus', native_enum=False, length=20), nullable=False, comment='배포 상태'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='배포 시작 시간'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='배포 완료 시간'),
    sa.Column('environment', sa.String(length=50), nullable=False, comment='배포 환경 (dev, staging, production)'),
    sa.Column('rollback_from_id', sa.Integer(), nullable=True, comment='롤백 대상 배포 ID'),
    sa.Column('notes', sa.Text(), nullable=True, comment='배포 메모'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='에러 메시지 (실패 시)'),
    sa.Column('log_url', sa.String(length=500), nullable=True, comment='배포 로그 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['deployed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rollback_from_id'], ['deployments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_environment'), 'deployments', ['environment'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False, comment='스프린트 ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='프로젝트 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='스프린트 이름'),
    sa.Column('goal', sa.Text(), nullable=True, comment='스프린트 목표'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='시작일'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='종료일'),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='sprintstatus', native_enum=False, length=20), nullable=False, comment='스프린트 상태'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sprints_status'), 'sprints', ['status'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False, comment='이슈 ID'),
    sa.Column('project_id', sa.Integer(), nullable=False, comment='프로젝트 ID'),
    sa.Column('sprint_id', sa.Integer(), nullable=True, comment='스프린트 ID'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='담당자 ID'),
    sa.Column('creator_id', sa.Integer(), nullable=False, comment='생성자 ID'),
    sa.Column('key', sa.String(length=20), nullable=False, comment='이슈 키 (예: PROJ-123)'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='이슈 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='이슈 설명'),
    sa.Column('type', sa.Enum('TASK', 'BUG', 'FEATURE', 'IMPROVEMENT', 'EPIC', name='issuetype', native_enum=False, length=20), nullable=False, comment='이슈 타입'),
    sa.Column('priority', sa.Enum('LOWEST', 'LOW', 'MEDIUM', 'HIGH', 'HIGHEST', name='issuepriority', native_enum=False, length=20), nullable=False, comment='우선순위'),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'TESTING', 'DONE', 'CLOSED', name='issuestatus', native_enum=False, length=20), nullable=False, comment='상태'),
    sa.Column('estimate_hours', sa.Integer(), nullable=True, comment='예상 소요 시간 (시간)'),
    sa.Column('actual_hours', sa.Integer(), nullable=True, comment='실제 소요 시간 (시간)'),
    sa.Column('order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_key'), 'issues', ['key'], unique=True)
    op.create_index(op.f('ix_issues_priority'), 'issues', ['priority'], unique=False)
    op.create_index(op.f('ix_issues_status'), 'issues', ['status'], unique=False)
    op.create_index(op.f('ix_issues_type'), 'issues', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issues_type'), table_name='issues')
    op.drop_index(op.f('ix_issues_status'), table_name='issues')
    op.drop_index(op.f('ix_issues_priority'), table_name='issues')
    op.drop_index(op.f('ix_issues_key'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_sprints_status'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_services_type'), table_name='services')
    op.drop_index(op.f('ix_services_status'), table_name='services')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_key'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_authentik_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_slug'), table_name='teams')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_servers_type'), table_name='servers')
    op.drop_index(op.f('ix_servers_status'), table_name='servers')
    op.drop_index(op.f('ix_servers_name'), table_name='servers')
    op.drop_index(op.f('ix_servers_environment'), table_name='servers')
    op.drop_table('servers')
    # ### end Alembic commands ###
